# Your Name or Company
title: Nikola Savic

# Description of your website. This is used for social sharing.
description:  Personal website for Nikola Savic.

# A brief blurb about yourself
content: I'm a software engineer and technical consultant at ThoughtWorks with an interest in intelligent systems and data engineering.

# Add your social links
social:
  - platform: github
    url: https://github.com/nikolasavic
  - platform: twitter
    url: https://twitter.com/not_nikolatesla
  - platform: linkedin
    url: https://www.linkedin.com/in/nikolasavic
  - platform: lichess
    url: https://lichess.org/@/notNikolaTesla

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
# sharing_image: share.jpg
# google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: left # left, right or center
